spring:
  application:
    name: marketplace
  datasource:
    # Thêm ?createDatabaseIfNotExist=true để tự tạo DB nếu chưa có
    url: jdbc:mysql://localhost:3306/TALLT_SoftwareMarket?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "123"
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        # QUAN TRỌNG: Giữ nguyên tên bảng viết Hoa (Users thay vì users)
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

# Cấu hình JWT tự quản (Nimbus). Secret key phải đủ dài cho HS512 (tối thiểu 64 ký tự).
jwt:
  signerKey: "DayLaMotChuoiBiMatRatDaiVaPhucTapDeMaHoaTokenChuyenDungChoProjectMarketplaceNhom5"
  valid-duration: 3600  # Thời gian sống token: 3600 giây = 1 tiếng